[workspace]
members = ["helper-lib", "main-lib"]

[patch.crates-io]
# We can remove my fork once openssl-sys points at openssl-src 300+
openssl-sys = { git="https://github.com/wez/rust-openssl.git", branch="openssl-src-300" }

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
