[package]
name = "main-lib"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
helper-lib = { path = "../helper-lib" }
mlua = { version = "0.6.6", features = ["async", "macros", "module", "serialize", "lua51", "vendored"] }
