[package]
name = "helper-lib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wezterm-ssh = { git = "https://github.com/wez/wezterm", features = ["vendored-openssl"] }
